# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('serial', models.TextField(null=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'achat")),
                ('purchase_price', models.CharField(max_length=9, verbose_name="Prix d'achat")),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=400)),
                ('contact', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Location'),
        ),
    ]
